version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: rake build
      - run: rake install
      - run: cd test/idiot
      - run: handsome_fencer-circle_c_i dockerize
      - run: docker-compose run rails new . --database=postgresql
      - run: docker-compose up -d
